apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: test-gpu
spec:
  nodeSelector:
    accelerator: nvidia-tesla-m6
  containers:
    - name: cuda-container
      image: nvidia/cuda
      resources:
        limits:
          nvidia.com/gpu: 1
      command: ["sh", "-c", "nvidia-smi; sleep 36000"]
