---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tf-jupyter4
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tf-jupyter4
    spec:
      nodeSelector:
        accelerator: nvidia-tesla-m6
      volumes:
      - hostPath:
          path: /usr/bin
        name: bin
      - hostPath:
          path: /usr/lib
        name: lib
      containers:
      - name: tensorflow4
        image: tensorflow/tensorflow:1.12.0-gpu
        ports:
        - containerPort: 8888
        resources:
          limits:
            # MiB
            aliyun.com/gpu-mem: 4064
#            aliyun.com/gpu-count: 1
        volumeMounts:
        - mountPath: /usr/local/nvidia/bin
          name: bin
        - mountPath: /usr/local/nvidia/lib
          name: lib
---
apiVersion: v1
kind: Service
metadata:
  name: tf-jupyter-service4
  labels:
    app: tf-jupyter4
spec:
  selector:
    app: tf-jupyter4
  ports:
  - port: 8888
    protocol: TCP
    nodePort: 30064
  type: LoadBalancer
---

